### ISSUE TITLE
Display text of current todo text when you press Edit 

### ISSUE THREAD

**Issue by paolotormon** [rcminerva2394/simple-todo#1]
At the moment it shows an empty input field when I edit

![image](https://user-images.githubusercontent.com/61226023/170874054-f3416844-ee7d-4e39-8362-85948abf46a3.png)
![image](https://user-images.githubusercontent.com/61226023/170874066-cfdc3f0b-40dc-4292-b568-49956e425bdf.png)

**Comment by rcminerva2394** [comment]
Thanks, Paolo! It's updated already :)
